# Generated by Django 5.0.5 on 2024-06-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviwe',
            new_name='Review',
        ),
    ]
